NumPy is the core library for scientific in Python. It is informally known as the swiss army knife of the data scientist
It provides a high-performance multidimensional array object numpy.ndarray, and tools for operating on these arrays.
If you’re already familiar with numerical processing in a different language like MATLAB and R, here are some recommended references:
https://numpy.org/doc/stable/user/numpy-for-matlab-users.html
http://www.data-analysis-in-python.org/python_for_r.html
Related primers: https://aman.ai/primers/matplotlib and https://aman.ai/primers/scipy.


## Arrays
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers.
The rank of an array is the number of dimensions it contains.
The shape of an array is a tuple of integers giving the size of the array along each dimension.
The size of an array is the number of elements it contains (which is equivalent to np.prod(<ndarray>.shape), i.e., the product of the array’s dimensions).
We can initialize NumPy arrays from (nested) lists and tuples, and access elements using square brackets as array subscripts (similar to lists in Python).

In [22]:
import numpy as np
a = np.array([1, 2, 3])                     # Define a rank 1 array using a list
print(type(a))                              # Prints <class 'numpy.ndarray'>
print(a.shape)                              # (3,)
print(a.ndim)                               # Prints 1 (the rank ò the array); equivalent to "len(a.shape)"
print(a.size)                               # Prints 3; equivalent to "np.prob(a.shape)"
print(a[0], a[1], a[2])                     # Print (1, 2, 3)
a[0] = 5                                    # Change an element of the array
print(a)

b = np.array([[1, 2, 3]])                   # Define a rank 2 array (vector) using a nested list
print(b.shape)                              # (1, 3)
print(b.size)                               # 3

c = np.array([[1, 2, 3], [4, 5, 6]])        # Define a rank 2 array (matrix) using a nested list
print(c.shape)                              # (2, 3)
print(c[0, 0], c[0, 1], c[1,0])             # 1 2 4

d = np.array((1,2,3))                       # Define a rank 1 array using a tuple
print(d)                                    # [1 2 3]
print(d.shape)                              # (3,)

e = np.array(((1,2,3),(4,5,6)))             # Define a rank 2 using a nested tuple
print(e)                                    # [[1 2 3]
                                            # [4 5 6]]

f = np.array([[1,2,3], [4,5,]])               # Define a rank 2 array using
print(f)



<class 'numpy.ndarray'>
(3,)
1
3
1 2 3
[5 2 3]
(1, 3)
3
(2, 3)
1 2 4
[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.